### ISSUE TITLE
Error creating artifactory service endpoint -unable to find service connection type 'artifactoryService'

### ISSUE THREAD

**Issue by andywilde** [pulumi/pulumi-azuredevops#150]
### What happened?

When trying create an endpoint to Artifactory following the example https://www.pulumi.com/registry/packages/azuredevops/api-docs/serviceendpointartifactory/ ) I encounter this error with username/password specified:

```
Error creating service endpoint in Azure DevOps: Unable to find service connection type 'artifactoryService' using authentication scheme 'UsernamePassword'.
```
or this error with a token:
```
Error creating service endpoint in Azure DevOps: Unable to find service connection type 'artifactoryService' using authentication scheme 'Token'.
```

### Expected Behavior

Expect the service connection to Artifactory to be created using username/password or token.

### Steps to reproduce

Create a project and artifactory endpoint using username/password:

```
 example_project = azuredevops.Project("exampleProject",
        visibility="private",
        version_control="Git",
        work_item_template="Agile",
        description="Managed by Terraform")
    example_service_endpoint_artifactory = azuredevops.ServiceEndpointArtifactory("exampleServiceEndpointArtifactory",
        project_id=example_project.id,
        service_endpoint_name="Example Artifactory",
        description="Managed by Terraform",
        url="https://xxxx.jfrog.io/artifactory",
        authentication_basic=azuredevops.ServiceEndpointArtifactoryAuthenticationBasicArgs(
            username="azdo-user",
            password="XXXXXXXX",
        ))
```
Then try to use the token instead:

```
 example_project = azuredevops.Project("exampleProject",
        visibility="private",
        version_control="Git",
        work_item_template="Agile",
        description="Managed by Terraform")
    example_service_endpoint_artifactory = azuredevops.ServiceEndpointArtifactory("exampleServiceEndpointArtifactory",
        project_id=example_project.id,
        service_endpoint_name="Example Artifactory",
        description="Managed by Terraform",
        url="https://xxxx.jfrog.io/artifactory",
        authentication_token=azuredevops.ServiceEndpointArtifactoryAuthenticationTokenArgs(
            token="XXXX",
        ))
```

### Output of `pulumi about`

LI          
Version      3.64.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME         VERSION
azuredevops  2.6.0
command      0.7.1
python       unknown

Host     
OS       mariner
Version  2.0.20230321
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.9.14
'

Current Stack: dev

TYPE                                                                           URN
pulumi:pulumi:Stack                                                            urn:pulumi:dev::ado::pulumi:pulumi:Stack::ado-dev
pulumi:providers:azuredevops                                                   urn:pulumi:dev::ado::pulumi:providers:azuredevops::default_2_6_0
azuredevops:index/project:Project                                              urn:pulumi:dev::ado::azuredevops:index/project:Project::pulumi_test
azuredevops:index/project:Project                                              urn:pulumi:dev::ado::azuredevops:index/project:Project::platform_engineering
azuredevops:index/project:Project                                              urn:pulumi:dev::ado::azuredevops:index/project:Project::exampleProject
azuredevops:index/branchPolicyCommentResolution:BranchPolicyCommentResolution  urn:pulumi:dev::ado::azuredevops:index/branchPolicyCommentResolution:BranchPolicyCommentResolution::pulumi_test_branchPolicyCommentResolution
azuredevops:index/branchPolicyWorkItemLinking:BranchPolicyWorkItemLinking      urn:pulumi:dev::ado::azuredevops:index/branchPolicyWorkItemLinking:BranchPolicyWorkItemLinking::pulumi_test_branchPolicyWorkItemLinking
azuredevops:index/buildFolder:BuildFolder                                      urn:pulumi:dev::ado::azuredevops:index/buildFolder:BuildFolder::pulumi_test_buildFolder
azuredevops:index/environment:Environment                                      urn:pulumi:dev::ado::azuredevops:index/environment:Environment::pulumi_test_exampleEnvironment
azuredevops:index/branchPolicyWorkItemLinking:BranchPolicyWorkItemLinking      urn:pulumi:dev::ado::azuredevops:index/branchPolicyWorkItemLinking:BranchPolicyWorkItemLinking::platform_engineering_branchPolicyWorkItemLinking
azuredevops:index/branchPolicyCommentResolution:BranchPolicyCommentResolution  urn:pulumi:dev::ado::azuredevops:index/branchPolicyCommentResolution:BranchPolicyCommentResolution::platform_engineering_branchPolicyCommentResolution
azuredevops:index/serviceEndpointAzureRM:ServiceEndpointAzureRM                urn:pulumi:dev::ado::azuredevops:index/serviceEndpointAzureRM:ServiceEndpointAzureRM::platform_engineering_serviceEndpointAzureRM

Found no pending operations associated with dev

Backend        
Name           cc-578e217a-6577ddc5f8-9nxx5
URL            azblob://pulumistate
User           lv66679
Organizations  

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's dependencies: illegal semver returned by language host: mssql-scripter@1.0.0a23: Invalid character(s) found in patch number "0a23"

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Hi @andywilde , it looks like this was a known issue in the upstream provider that has now been resolved (see https://github.com/microsoft/terraform-provider-azuredevops/pull/705). This should be available once the next version is released upstream.

**Comment by aq17** [comment]
@andywilde just checking in on this, this should be fixed with the latest version of the provider. Would you mind confirming that your issue is resolved?

**Comment by andywilde** [comment]
hi @aq17, unfortunately I'm still getting this error:
```
 error: 1 error occurred:
        * Error creating service endpoint in Azure DevOps: Unable to find service connection type 'artifactoryService' using authentication scheme 'Token'.
```
and according to `pulumi about` I'm on the latest provider version:
```
CLI          
Version      3.72.2
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.102.0
azuredevops   2.8.0
command       0.7.2
github        5.10.0
python        unknown

Host     
OS       mariner
Version  2.0.20230426
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.9.14
'

```
